from bidict import bidict

AOTY_URL_ROOT = "https://www.albumoftheyear.org/publication/57-the-needle-drop/reviews/1/"
FANTANO_WEBSITE_URL_ROOT = "https://theneedledrop.com/"
MELONDY_URL = "https://melondy.com"
CRAWLER_COOKIE_NAME="session_id"
CRAWLER_COOKIE_VALUE="your_token_here"
MELONDY_TO_SPOTIFY={
    "album_name": {
        "春火燎原": "SHUNKA RYOUGEN",
        "Twin Fantasy (Face to Face)": "Twin Fantasy",
        "Higher Learning Vol. 2": "Higher Learning 2",
        "魔法学校": "Mahōgakkō",
        "ATUM: A Rock Opera in Three Acts": "ATUM",
        "ピカピカふぁんたじん": "Pika Pika Fantajin",
        "春と修羅": "Haru to Shura",
        "Jxmtro": "SR3MM",
        "Earth 2: Special Low Frequency Version": "Earth 2.23: Special Lower Frequency Version",
        "All Delighted People EP": "All Delighted People",
        "破爛酒店 (Hotel la Rut)": "Hotel la Rut (破爛酒店)",
        "Lil B.I.G. Pac": "Lil Big Pac",
        "A Special Episode Of": "A Special Episode - EP",
        "Angels of Darkness, Demons of Light II": "Angels of Darkness, Demons of Light 2",
        "Angels of Darkness, Demons of Light I": "Angels of Darkness, Demons of Light 1",
        "Belle and Sebastian Write About Love": "Write About Love",
        "99.90%": "99.9%",
        "... And Star Power": "...And Star Power",
        "Im All Ears": "I'm All Ears",
        "Fingers, Bank Pads, and Shoe Prints": "Fingers, Bank Pads, & Shoe Prints",
        "Everything Not Saved Will Be Lost, Part 1": "Everything Not Saved Will Be Lost Part I",
        "Un canto por México, vol. 2": "Un canto por México, vol. II",
        "Hot Sauce Committee, Part Two": "Hot Sauce Committee (Pt. 2)",
        "111111": "11•11•11",
        "Ἀποκάλυψις": "Apokalypsis",
        "FUCK U SKRILLEX YOU THINK UR ANDY WARHOL BUT UR NOT!! <3": "F*CK U SKRILLEX YOU THINK UR ANDY WARHOL BUT UR NOT!! <3",
        "Hoax [3rd EP]": "Stuck",
        "Makthaverskan II": "II",
        "= [equals]": "=",
        "- [subtract]": "-",
        "New History Warfare, Volume 3: To See More Light": "New History Warfare Vol. 3: To See More Light",
        "New History Warfare, Volume 2: Judges": "New History Warfare Vol. 2: Judges",
        "★ [Blackstar]": "Blackstar",
        "アダンの風": "Windswept Adan",
        "32 Zel / Planet Shrooms": "32 Zel",
        "Decompositions, Volume Number One": "Decompositions, Vol. 1",
        "The Scars of Man on the Once Nameless Wilderness I and II": "The Scars of Man on the Once Nameless Wilderness, Pt. 2",
        "Miles: From an Interlude Called Life": "Miles",
        "Father of All Motherfuckers": "Father of All...",
        "dDemonstrator": "Shobaleader One: D'Demonstrator",
        "CITY MORGUE, VOLUME 2: AS GOOD AS DEAD": "CITY MORGUE, VOL 2: AS GOOD AS DEAD",
        "Volume 1: Flick Your Tongue Against Your Teeth and Describe the Present.": "Vol 1: Flick Your Tongue Against Your Teeth and Describe the Present"
    },
    "artist_name": {
        "春ねむり": "HARU NEMURI",
        "The Jimi Hendrix Experience": "Jimi Hendrix",
        "Silk Sonic": "Bruno Mars",
        "きゃりーぱみゅぱみゅ": "Kyary Pamyu Pamyu",
        "Scott Walker & Sunn O)))": "Scott Walker",
        "長谷川白紙": "Hakushi Hasegawa",
        "Andrew Jackson Jihad": "AJJ",
        "Machine Gun Kelly": "MGK",
        "Viet Cong": "Preoccupations",
        "おとぼけビ〜バ〜": "Otoboke Beaver",
        "Sufjan Stevens & Nico Muhly & Bryce Dessner & James McAlister": "Bryce Dessner",
        "Slim Jxmmi": "Rae Srummond",
        "Iggy and The Stooges": "The Stooges",
        "Moor Mother & billy woods": "billy woods",
        "王若琳": "Joanna Wang",
        "Osees": "Thee Oh Sees",
        "Himanshu": "Heems",
        "Alice Coltrane & Pharoah Sanders": "Alice Coltrane",
        "A Silver Mt. Zion": "Silver Mt. Zion",
        "billy woods & Messiah Musik": "billy woods",
        "박지하": "Park Jiha",
        "Jeffrey Lewis & The Deposit Returners": "Jeffrey Lewis",
        "The Knife & Mount Sims & Planningtorock": "The Knife",
        "Rob Scallon & Doug Walker": "Doug Walker",
        " Christian Scott aTunde Adjuah": "Chief Adjuah",
        "grouptherapy.": "PARTYOF2",
        "death's dynamic shroud.wmv": "death's dynamic shroud",
        "YC the Cynic": "Kemba",
        "D'Angelo & The Vanguard": "D'Angelo",
        "Elucid": "E L U C I D",
        "青葉市子": "Ichigo Aoba",
        "김예림": "Lim Kim",
        "파란노을": "Parannoul",
        "The UV Rave": "UV Race",
        "Keiji Haino & SUMAC": "SUMAC",
        "Girl Talk & Freeway": "Freeway",
        "Shobaleader One": "Squarepusher",
        "WestsideGunn": "Westside Gunn",
        "This Town Needs Guns": "TTNG",
        "Donnie Trumpet": "Nico Segal",
        "Donnie Trumpet & The Social Experiment": "Nico Segal",
        "Floating Points & Pharoah Sanders & The London Symphony Orchestra": "Floating Points",
    }
}