_target_: FantAIno.models.radius_neighbors_regressor.RadiusNeighborsRegressionModel
radius: 5
param_grid: 
    radius: [2, 5, 10, 25]
    weights: ["uniform", "distance"]
    p: [1, 2]
scoring_method: neg_mean_squared_error
model_run_name: grid
n_jobs: 4