_target_: FantAIno.models.radius_neighbors.RadiusNeighborsModel
mode: classification
radius: 1000
param_grid: 
    radius: [200, 500, 1000, 2500]
    weights: ["uniform", "distance"]
    p: [1, 2]
scoring_method: accuracy
model_run_name: grid_search
n_jobs: 4