_target_: FantAIno.models.radius_neighbors_classifier.RadiusNeighborsModel
mode: classification
radius: 100
param_grid: 
    radius: [20, 50, 100, 250]
    weights: ["uniform", "distance"]
    p: [1, 2]
scoring_method: accuracy
model_run_name: grid_search
n_jobs: 4