_target_: FantAIno.models.knn_classifier.KNNClassificationModel
n_neighbors: 5
param_grid: 
    n_neighbors: [2, 5, 10, 25]
    weights: ["uniform", "distance"]
    p: [1, 2]
scoring_method: accuracy
model_run_name: grid_search
n_jobs: 4