_target_: FantAIno.models.neighborhood_components.NeighborhoodComponentsModel
mode: classification
n_neighbors: 5
nca_components: 5
param_grid: null
scoring_method: accuracy
model_run_name: base
n_jobs: 4