_target_: FantAIno.models.catboost_regressor.CatBoostRegressionModel
iterations: 100
depth: 3
loss_fn: RMSE
learning_rate: 0.01
param_grid: null
scoring_method: neg_mean_squared_error
model_run_name: base
n_jobs: 4