_target_: FantAIno.models.random_forest_classifier.RandomForestClassificationModel
n_estimators: 100
param_grid: 
    n_estimators: [100, 250, 500, 1000]
    min_samples_leaf: [1, 2, 3, 5, 10, 25]
    max_features: [1.0, "sqrt", "log2", 0.75, 0.6, 0.2]
    min_impurity_decrease: [0.0, 0.001, 0.01, 0.1]
scoring_method: accuracy
model_run_name: grid
n_jobs: 4